services:
  app:
    image: oven/bun

    volumes:
      - ./app:/.

    working_dir: /app

    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"

    command: sh -c "chmod +x ./start.sh && ./start.sh"